### ISSUE TITLE
Unable to install hurl 4.1.0 because release binary filenames were changed

### ISSUE THREAD

**Issue by mystix** [raimon49/asdf-hurl#2]
**Describe the bug**
Unable to install hurl 4.1.0 because release binary filenames have changed starting from the 4.1.0 release.
Reference: https://github.com/Orange-OpenSource/hurl/issues/1951

**OS**
```
❯ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
```

**Steps to reproduce**
```
❯ asdf install hurl 4.1.0
```

**Expected behavior**
```
* Downloading hurl release 4.1.0...
hurl 4.1.0 installation was successful!
```

**Actual behaviour**
```
* Downloading hurl release 4.1.0...
curl: (22) The requested URL returned error: 404
asdf-hurl: Could not download https://github.com/Orange-OpenSource/hurl/releases/download/4.1.0/hurl-4.1.0-x86_64-linux.tar.gz
```

**Comment by raimon49** [comment]
Thanks for the detailed report.

I see that the filenames of the distribution has changed since hurl v4.1.0.

A bit of ad-hoc handling seems necessary. I will try to find time to do it.

**Comment by raimon49** [comment]
@mystix This issue has been fixed. 

Please try with the latest asdf-hurl.

```bash
$ asdf plugin update hurl
Updating hurl to main
From https://github.com/raimon49/asdf-hurl
   16dfd6c..d516669  main       -> main
   16dfd6c..d516669  main       -> origin/main
Already on 'main'
Your branch is up to date with 'origin/main'.

$ asdf install hurl 4.1.0
* Downloading hurl release 4.1.0...
hurl 4.1.0 installation was successful!
```

**Comment by mystix** [comment]
Tested and confirmed it works 👍 

Thanks for the quick fix @raimon49 !
